// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj49-jQ_fSE2fq3Gbwht5Ny7MsZvc0UoQ',
    appId: '1:131387665700:web:3cfe97a5da5920650817b1',
    messagingSenderId: '131387665700',
    projectId: 'hazyaeva-c5211',
    authDomain: 'hazyaeva-c5211.firebaseapp.com',
    storageBucket: 'hazyaeva-c5211.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2U07ChWijoX7fsrsOt8nGFBd_sLgJSBg',
    appId: '1:131387665700:android:6efca20df0d1edd50817b1',
    messagingSenderId: '131387665700',
    projectId: 'hazyaeva-c5211',
    storageBucket: 'hazyaeva-c5211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzk3ZsTexlOkq1taFNqDRYa8-50ZDXi8w',
    appId: '1:131387665700:ios:d8d70e73294f9b4f0817b1',
    messagingSenderId: '131387665700',
    projectId: 'hazyaeva-c5211',
    storageBucket: 'hazyaeva-c5211.appspot.com',
    androidClientId: '131387665700-p6a3r9po8b167vh07r7geq7uesjosk9f.apps.googleusercontent.com',
    iosClientId: '131387665700-0th8jbdeg59ujl566ploseqlsrj66h70.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniCasino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzk3ZsTexlOkq1taFNqDRYa8-50ZDXi8w',
    appId: '1:131387665700:ios:d8d70e73294f9b4f0817b1',
    messagingSenderId: '131387665700',
    projectId: 'hazyaeva-c5211',
    storageBucket: 'hazyaeva-c5211.appspot.com',
    androidClientId: '131387665700-p6a3r9po8b167vh07r7geq7uesjosk9f.apps.googleusercontent.com',
    iosClientId: '131387665700-0th8jbdeg59ujl566ploseqlsrj66h70.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniCasino',
  );
}
